name: Deployment auf die Testing EC2 Maschinen

on: 
  push:
    tags:
      - 'test-v*'
jobs:
    deploy-test:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v5

            - name: ssh setup
              run: | 
                mkdir -p ~/.ssh
                echo "${{secrets.SSH_PRIVATE_KEY}}" > ~/.ssh/meinPrivateKey
                chmod 400 ~/.ssh/meinPrivateKey

                for ip in ${{secrets.EC2_TESTING_IPS}}; do
                    ssh-keyscan -H $ip >> ~/.ssh/known_hosts
                done

            - name: deploy Website on all EC2 instances
              run: |
                for ip in ${{secrets.EC2_TESTING_IPS}}; do
                    scp -i ~/.ssh/meinPrivateKey website/index.html ubuntu@$ip:/home/ubuntu/index.html
                    ssh -i ~/.ssh/meinPrivateKey ubuntu@$ip "sudo cp /home/ubuntu/index.html /var/www/html/index.html"
                done
                
